name: DeCoudre
version: ${pluginVersion}
description: ${properties.description}
author: syldium

main: me.syldium.decoudre.bukkit.DeCoudreBootstrap
api-version: 1.13
softdepend: [Parties, PlaceholderAPI]

commands:
  dac:
    usage: /dac <join|leave> [args]

permissions:
  decoudre.arena.*:
    default: op
    description: Grant access to commands to edit arenas.
    children:
      decoudre.arena.create: true
      decoudre.arena.set.gamemode: true
      decoudre.arena.set.jump: true
      decoudre.arena.set.max.players: true
      decoudre.arena.set.min.players: true
      decoudre.arena.set.spawn: true
  decoudre.player.*:
    default: true
    description: Allows players to play in arenas.
    children:
      decoudre.player.block: true
      decoudre.player.join: true
      decoudre.player.leave: true
